### ISSUE TITLE
As a single roomie, I want to be able to complete my personal profile, in order to provide accurate information for flats so that they want me as their new flatmate

### ISSUE THREAD

**Issue by larsuzh** [sopra-fs22-group-21/roomeight-backend#10]
**Definition of done**: Acceptance Criteria:
- [x] After creation of the profile, I want to have the option to insert further data about myself.
- [x] I should be able to input:
   -	tags about my Hobbies / Interests
   -	Pictures of myself
   -    Gender
   -    Move-in Date
   -	Description / application / message
   -    Biography
- [x] Afterwards, I get access to all the functionality of the app.

**Development Tasks**
- [x] sopra-fs22-group-21/roomeight-frontend#10
- [x] sopra-fs22-group-21/roomeight-backend#43
- [x] sopra-fs22-group-21/roomeight-backend#44
- [x] sopra-fs22-group-21/roomeight-backend#45
