### ISSUE TITLE
 As a user (in regards of my status), I want to be able to discover the profiles of people or flats respectively, in order to find the perfect match

### ISSUE THREAD

**Issue by larsuzh** [sopra-fs22-group-21/roomeight-backend#12]
**Definition of done**: Acceptance Criteria:
- [x] `profiles of the other type are displayed (one at a time)`
- [x] `upon liking / disliking, the next profile is shown`

**Development Tasks**
- [x] sopra-fs22-group-21/roomeight-backend#69
- [x] sopra-fs22-group-21/roomeight-frontend#11
- [x] sopra-fs22-group-21/roomeight-frontend#12
