### ISSUE TITLE
As a user (single or belonging to a flat), I want to be able to edit my search criteria on the discover page search settings, in order to customise which people should be displayed on the discover page

### ISSUE THREAD

**Issue by larsuzh** [sopra-fs22-group-21/roomeight-backend#15]
**Definition of done**: Acceptance Criteria:
- [x] As a user (single or flat), I want to be able to set the following values for the search (both are optional)
   - `gender`
   - `age range (at least 4 years)` 
   -  `tags of hobbies/interests`
   -   `Move-in Date`
- [x] These changes should be saved permanently
- [x] Different roomies can have different filters.

**Development Tasks:**
- [x] sopra-fs22-group-21/roomeight-frontend#26
- [x] sopra-fs22-group-21/roomeight-frontend#27
- [x] sopra-fs22-group-21/roomeight-frontend#28
- [x] #91
- [x] #92
- [x] #93
