### ISSUE TITLE
As a user, I want to be able match with profiles I like and that like me back, in order to find a new roomie / flat

### ISSUE THREAD

**Issue by larsuzh** [sopra-fs22-group-21/roomeight-backend#17]
**Definition of done**: Acceptance Criteria:
- [x] `when I like profiles, if they like me back, a match should be generated and saved.`
- [x] `I should be informed that this is a match`

**Development Tasks**
- [x] sopra-fs22-group-21/roomeight-backend#56
- [x] sopra-fs22-group-21/roomeight-backend#57
- [x] sopra-fs22-group-21/roomeight-frontend#14
