### ISSUE TITLE
As a new User of the Application, I want to be able to create a profile in the app, in order to search for a flatmate or find a flat

### ISSUE THREAD

**Issue by luisauzh** [sopra-fs22-group-21/roomeight-backend#2]
**Definition of done**: Acceptance Criteria:
- [x] I should be able to input:
   -  Firstname
   - Lastname
   - Email
   - Phone 
   - Birthday
   - Password
   - Gender
- [x] Afterwards I should be logged in and my profile should be registered.

**Development Tasks**
- [x] sopra-fs22-group-21/roomeight-backend#27
- [x] sopra-fs22-group-21/roomeight-backend#28
- [x] sopra-fs22-group-21/roomeight-backend#29
- [x] sopra-fs22-group-21/roomeight-frontend#20
- [x] sopra-fs22-group-21/roomeight-frontend#3
- [x] sopra-fs22-group-21/roomeight-frontend#4
