### ISSUE TITLE
 As a user (flat or person), I want to be able to chat with my matches, in order to get in contact with them

### ISSUE THREAD

**Issue by luisauzh** [sopra-fs22-group-21/roomeight-backend#20]
**Definition of done**: Acceptance Criteria:
- [x] `I can see all the messages exchanged in the past`
- [x] `I can send messages`
- [x] `As soon as someone sends me a message, it is visible in the chat`
- [x] `I get notified whenever I receive a message`
- [x] `I see the status <online> or <offline> whenever chatting with a profile`

**Development Tasks**
- [x] sopra-fs22-group-21/roomeight-frontend#17
- [x] sopra-fs22-group-21/roomeight-frontend#30
- [x] sopra-fs22-group-21/roomeight-frontend#44
- [x] sopra-fs22-group-21/roomeight-frontend#45
- [x] sopra-fs22-group-21/roomeight-backend#108 
- [x] sopra-fs22-group-21/roomeight-backend#109
- [x] #111
