### ISSUE TITLE
As a single roomie, I want to be able to see all my flat matches on a map, in order to see which one is located where.

### ISSUE THREAD

**Issue by luisauzh** [sopra-fs22-group-21/roomeight-backend#22]
**Definition of done**: Acceptance Criteria:
- [x] `on the matches page of a single roomie, if there are matches, a map should display all of them`
- [x] `upon clicking on a pin, I should see which flat it is and be able to navigate to the public profile of that flat`

**Development Tasks:**

- [x] sopra-fs22-group-21/roomeight-frontend#32
- [x] sopra-fs22-group-21/roomeight-frontend#33
- [x] sopra-fs22-group-21/roomeight-frontend#35
