### ISSUE TITLE
As a flatmate, I want to be notified when my flat liked a single roomie, in order to be able to collaborate with my flat in real time, generate faster matches for single roomies (because of asynchrony of matching) and make sure that every person of the flat sees as many matches as possible.

### ISSUE THREAD

**Issue by luisauzh** [sopra-fs22-group-21/roomeight-backend#23]
**Definition of done**: Acceptance Criteria:
- [x] `While I'm online , if someone else has generated a match, the single roomie's profile is instantly shown (independently of the page I'm on) and I have to like/dislike the person`
- [x] `Additionally to the profile, the person who has created the match (either the last flatmate oder the single roomie) is displayed`

**Development Tasks**
- [x] sopra-fs22-group-21/roomeight-frontend#37
- [x] sopra-fs22-group-21/roomeight-frontend#39
- [x] sopra-fs22-group-21/roomeight-frontend#40
