### ISSUE TITLE
As a user belonging to a flat, I want to be able to see how many roommates of my flat have already liked a person, in order to generate more matches

### ISSUE THREAD

**Issue by luisauzh** [sopra-fs22-group-21/roomeight-backend#24]
**Definition of done**: Acceptance Criteria:

_As a user belonging to a flat I want to be able to_
- [x] `see how many roommates of my flat have already matched the person that gets displayed to me on the discover page.`
- [x] `see how many roommates of my flat have already matched the person which appears on the match page.`

**Development Tasks**
- [x] sopra-fs22-group-21/roomeight-frontend#29
- [x] sopra-fs22-group-21/roomeight-frontend#42
- [x] sopra-fs22-group-21/roomeight-frontend#34
- [x] sopra-fs22-group-21/roomeight-frontend#36
- [x] sopra-fs22-group-21/roomeight-frontend#38
