### ISSUE TITLE
 As a user, I want to be able to log out and log back in for privacy

### ISSUE THREAD

**Issue by luisauzh** [sopra-fs22-group-21/roomeight-backend#3]
**Definition of done**: Acceptance Criteria:
- [x] `There is a logout button`
- [x] `There is a login page from which the registration page can be reached`
- [x] `After logging in, I have access to all the functionality of the app according to my profile`

**Development Tasks**

- [x] sopra-fs22-group-21/roomeight-frontend#5
- [x] sopra-fs22-group-21/roomeight-frontend#21
- [x] sopra-fs22-group-21/roomeight-frontend#6
- [x] sopra-fs22-group-21/roomeight-frontend#19
