### ISSUE TITLE
As a registered User, I want to be able to create a single roomie or a flat profile, in order to provide information about myself and my search status

### ISSUE THREAD

**Issue by luisauzh** [sopra-fs22-group-21/roomeight-backend#5]
**Definition of done**: Acceptance Criteria:
- After registering, I need to complete my profile. For that, I choose between:
   - [x] creating a new flat (--> create flat profile, complete personal profile as flatmate)
   - [x] joining an existing flat (--> join flat, complete personal profile as flatmate)
   - [x] just completing my personal profile. (--> complete personal profile as roomie)
- [x] I will be redirected to the respective interface where this can be done. 
- [x] Afterwards, my status will be set to "looking for a flat" or "looking for a roomie"

**Development Tasks**
- [x] sopra-fs22-group-21/roomeight-frontend#7
- [x] sopra-fs22-group-21/roomeight-backend#40
- [x] sopra-fs22-group-21/roomeight-backend#41
