### ISSUE TITLE
As a User belonging to a flat, I want to be able to complete my personal profile, in order to provide accurate information for people so that they know with who they would live if they moved in

### ISSUE THREAD

**Issue by luisauzh** [sopra-fs22-group-21/roomeight-backend#6]
**Definition of done**: Acceptance Criteria:
- After creation of the profile, I want to have the option to insert further data about myself.
- I should be able to input:
   - [x] Tags about myself and my interests
   - [x] Pictures of myself
   - [x] Description / message
- Afterwards, I get access to all the functionality of the app.

**Development Tasks**
- [x] sopra-fs22-group-21/roomeight-frontend#8
- [x] sopra-fs22-group-21/roomeight-backend#43
- [x] sopra-fs22-group-21/roomeight-backend#44
- [x] sopra-fs22-group-21/roomeight-backend#45
