### ISSUE TITLE
As a registered User, I want to be able to create a flat profile in the app, in order to provide accurate information for people in search of a flat

### ISSUE THREAD

**Issue by luisauzh** [sopra-fs22-group-21/roomeight-backend#7]
**Definition of done**: Acceptance Criteria:
- After the creation of the profile, I want to have the option to insert further data about the flat.
- [x] I should be able to input:
   -   Pictures of the flat
   -	Pictures of the free room
   -	Room specifications (e.g. square meters, ...)
   -	Address
   -	Rent + additional cost
   -   number of roommates
   -   number of bathrooms
   -	Date from which the room will be available
   -	Date until which the room will be available
   -	Description

**Development Tasks**
- [x] sopra-fs22-group-21/roomeight-backend#46
- [x] sopra-fs22-group-21/roomeight-backend#47
- [x] sopra-fs22-group-21/roomeight-backend#48
- [x] sopra-fs22-group-21/roomeight-frontend#9
